### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kevmoo**
Using github to keep individual commits separate and clear

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/utf/3)

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @sgjesse 

Brining this package into the future a bit

**Comment by sgjesse** [comment]
@lrhn can you take a look?

**Comment by lrhn** [comment]
It's perfectly nice changes, but it's really lipstick on a pig. This library, if we want to support it, should be rewritten to be converters.

**Comment by kevmoo** [comment]
Absolutely!

The goal here: clean this up so it's easy to migrate and maintain the tests as we move to pkg/convert

**Pull request merged**
